don't use error message but check returncode of the command
olivierverdier/zsh-git-prompt pull request #119
Opened 2018-04-12 16:48 UTC by Segaja

using return code to find out if a folder is under git version control.

2018-04-20 08:46 UTC, Felixoid commented
Hello @olivierverdier 
Could you please merge this to fix annoying prompt in each folder on the shell?

2018-04-25 22:37 UTC, Felixoid requested changes

2018-04-25 22:37 UTC, Felixoid commented on gitstatus.py
> +if 0 != gitsym.returncode:
this change broke prompt like `(:de68074|✔)` on detached HEAD

2018-04-25 22:37 UTC, Felixoid commented on gitstatus.py
>  gitsym = Popen(['git', 'symbolic-ref', 'HEAD'], stdout=PIPE, stderr=PIPE)
There is most quick way to get info are we in git repo or not
```
isgit = Popen(['git', 'name-rev'], stdout=PIPE, stderr=PIPE)
_, _ = isgit.communicate()                                  
if isgit.returncode != 0:                                   
    sys.exit(0)                                             
```
IMO it should be right after `import sys`

2018-04-26 11:31 UTC, Felixoid commented on gitstatus.py
> +if 0 != gitsym.returncode:
If you'll add `if isgit.returncode != 0:`, then this code could be deleted

2018-04-28 08:31 UTC, Segaja commented
The problem is that the `git symbolic-ref HEAD` command also found the branch name and that is used later. so either I have to add another command to run or figure out how to do this with one command without breaking detached heads.

2023-12-07 09:15 UTC, closed without merging